-- ============================================================
-- V1: Baseline schema, sinh từ chính các entity JPA hiện tại
-- (Hibernate SchemaExport + PostgreSQLDialect) rồi chỉnh tay.
--
-- Khác biệt DUY NHẤT so với bản Hibernate sinh ra:
--   * bảng "user" -> "users". `user` là từ khoá RESERVED của
--     PostgreSQL, `create table user` là lỗi cú pháp. Đây cũng
--     là lý do entity Order đã có @Table(name = "orders").
--     Entity User nay có @Table(name = "users") tương ứng.
--   * tên constraint đặt lại cho dễ đọc (Hibernate sinh hash
--     kiểu FKel9kyl84ego2otj2accfd8mr7).
--
-- Kiểu cột phải khớp CHÍNH XÁC với entity vì ddl-auto đã đổi
-- sang `validate` — sai một kiểu là app không khởi động được.
-- ============================================================

-- ---------------------------- Bảng gốc, không FK ----------------------------

CREATE TABLE banner (
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    display_order integer,
    is_active     boolean,
    alt_text      varchar(255),
    button_text   varchar(255),
    image_url     TEXT,
    redirect_url  varchar(255),
    subtitle      varchar(255),
    title         varchar(255),
    created_at    timestamp(6),
    updated_at    timestamp(6),
    PRIMARY KEY (id)
);

CREATE TABLE brand (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(255),
    slug        varchar(255) NOT NULL UNIQUE,
    description TEXT,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    PRIMARY KEY (id)
);

CREATE TABLE category (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(255),
    slug        varchar(255) NOT NULL UNIQUE,
    description TEXT,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    PRIMARY KEY (id)
);

CREATE TABLE permission (
    name        varchar(255) NOT NULL,
    description varchar(255),
    PRIMARY KEY (name)
);

CREATE TABLE role (
    name        varchar(255) NOT NULL,
    description varchar(255),
    PRIMARY KEY (name)
);

CREATE TABLE invalidated_token (
    id          varchar(255) NOT NULL,
    type        varchar(255),
    expiry_time timestamp(6),
    PRIMARY KEY (id)
);

CREATE TABLE conversations (
    id              varchar(255) NOT NULL,
    channel         varchar(255) NOT NULL,
    guest_name      varchar(255) NOT NULL,
    status          varchar(255) NOT NULL,
    unread_count    integer      NOT NULL,
    last_message_at timestamp(6),
    created_at      timestamp(6),
    updated_at      timestamp(6),
    PRIMARY KEY (id)
);

CREATE TABLE chat_messages (
    id              varchar(255)  NOT NULL,
    conversation_id varchar(255)  NOT NULL,
    sender_type     varchar(255)  NOT NULL,
    content         varchar(2000) NOT NULL,
    created_at      timestamp(6),
    PRIMARY KEY (id)
);

CREATE TABLE post_categories (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(255) NOT NULL,
    slug        varchar(255) NOT NULL UNIQUE,
    description varchar(1000),
    created_at  timestamp(6),
    updated_at  timestamp(6),
    PRIMARY KEY (id)
);

CREATE TABLE professional_service (
    id                bigint GENERATED BY DEFAULT AS IDENTITY,
    name              varchar(255),
    slug              varchar(255),
    short_description TEXT,
    full_description  TEXT,
    features          TEXT,
    display_order     integer,
    created_at        timestamp(6),
    updated_at        timestamp(6),
    PRIMARY KEY (id)
);

-- `users` chứ không phải `user`: xem ghi chú đầu file.
CREATE TABLE users (
    id           varchar(255) NOT NULL,
    username     varchar(255) NOT NULL UNIQUE,
    password     varchar(255),
    email        varchar(255),
    full_name    varchar(255),
    phone_number varchar(255),
    avatar_url   varchar(255),
    google_id    varchar(255) UNIQUE,
    created_at   timestamp(6),
    updated_at   timestamp(6),
    PRIMARY KEY (id)
);

-- ---------------------------- Bảng có FK ----------------------------

CREATE TABLE product (
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    name           varchar(255),
    slug           varchar(255),
    description    TEXT,
    unit_price     numeric(38, 2),
    stock_quantity integer,
    brand_id       bigint,
    category_id    bigint,
    created_at     timestamp(6),
    updated_at     timestamp(6),
    PRIMARY KEY (id)
);

CREATE TABLE product_image (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint,
    image_url  varchar(255),
    alt_text   varchar(255),
    is_primary boolean,
    sort_order integer,
    created_at timestamp(6),
    updated_at timestamp(6),
    PRIMARY KEY (id)
);

CREATE TABLE service_image (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    service_id bigint,
    image_url  varchar(255),
    alt_text   varchar(255),
    is_primary boolean,
    sort_order integer,
    created_at timestamp(6),
    updated_at timestamp(6),
    PRIMARY KEY (id)
);

CREATE TABLE cart (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id    varchar(255) UNIQUE,
    created_at timestamp(6),
    updated_at timestamp(6),
    PRIMARY KEY (id)
);

CREATE TABLE cart_item (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    cart_id    bigint,
    product_id bigint,
    quantity   integer,
    created_at timestamp(6),
    updated_at timestamp(6),
    PRIMARY KEY (id)
);

CREATE TABLE orders (
    id                varchar(255)   NOT NULL,
    user_id           varchar(255)   NOT NULL,
    order_code        varchar(255)   NOT NULL UNIQUE,
    total_price       numeric(38, 2) NOT NULL,
    name_recipient    varchar(255)   NOT NULL,
    phone_recipient   varchar(255)   NOT NULL,
    address_recipient varchar(255)   NOT NULL,
    note              varchar(255),
    status            varchar(255)   NOT NULL CHECK (status IN ('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELED')),
    payment_method    varchar(255)   NOT NULL CHECK (payment_method IN ('COD', 'BANK_TRANSFER')),
    payment_status    varchar(255)   NOT NULL CHECK (payment_status IN ('UNPAID', 'PAID', 'REFUNDED')),
    created_at        timestamp(6),
    updated_at        timestamp(6),
    PRIMARY KEY (id)
);

CREATE TABLE order_detail (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id   varchar(255) NOT NULL,
    product_id bigint       NOT NULL,
    quantity   integer      NOT NULL,
    created_at timestamp(6),
    updated_at timestamp(6),
    PRIMARY KEY (id)
);

CREATE TABLE payments (
    id               bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id         varchar(255)   NOT NULL,
    amount           numeric(38, 2) NOT NULL,
    status           varchar(255)   NOT NULL CHECK (status IN ('UNPAID', 'PAID', 'REFUNDED')),
    gateway          varchar(255),
    account_number   varchar(255),
    reference_code   varchar(255),
    transaction_code varchar(255),
    transaction_date varchar(255),
    transfer_content varchar(255),
    created_at       timestamp(6),
    updated_at       timestamp(6),
    PRIMARY KEY (id)
);

CREATE TABLE posts (
    id                bigint GENERATED BY DEFAULT AS IDENTITY,
    title             varchar(500) NOT NULL,
    slug              varchar(500) NOT NULL UNIQUE,
    short_description varchar(1000),
    content           TEXT,
    thumbnail_url     varchar(255),
    published         boolean      NOT NULL,
    view_count        bigint,
    author_id         varchar(255),
    category_id       bigint,
    created_at        timestamp(6),
    updated_at        timestamp(6),
    PRIMARY KEY (id)
);

CREATE TABLE notifications (
    id           varchar(255) NOT NULL,
    user_id      varchar(255) NOT NULL,
    title        varchar(255) NOT NULL,
    message      varchar(500) NOT NULL,
    type         varchar(255) NOT NULL CHECK (type IN ('ORDER_CREATED', 'ORDER_STATUS_CHANGED', 'ORDER_CANCELED', 'PAYMENT_RECEIVED', 'SYSTEM')),
    reference_id varchar(255),
    is_read      boolean      NOT NULL,
    created_at   timestamp(6),
    updated_at   timestamp(6),
    PRIMARY KEY (id)
);

-- ---------------------------- Bảng nối (join tables) ----------------------------

CREATE TABLE category_brand (
    brand_id    bigint NOT NULL,
    category_id bigint NOT NULL,
    PRIMARY KEY (brand_id, category_id)
);

CREATE TABLE role_permissions (
    role_id        varchar(255) NOT NULL,
    permissions_id varchar(255) NOT NULL,
    PRIMARY KEY (permissions_id, role_id)
);

CREATE TABLE user_roles (
    user_id varchar(255) NOT NULL,
    role_id varchar(255) NOT NULL,
    PRIMARY KEY (role_id, user_id)
);

-- ---------------------------- Khoá ngoại ----------------------------

ALTER TABLE cart              ADD CONSTRAINT fk_cart_user              FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE cart_item         ADD CONSTRAINT fk_cart_item_cart         FOREIGN KEY (cart_id) REFERENCES cart (id);
ALTER TABLE cart_item         ADD CONSTRAINT fk_cart_item_product      FOREIGN KEY (product_id) REFERENCES product (id);
ALTER TABLE category_brand    ADD CONSTRAINT fk_category_brand_brand   FOREIGN KEY (brand_id) REFERENCES brand (id);
ALTER TABLE category_brand    ADD CONSTRAINT fk_category_brand_cat     FOREIGN KEY (category_id) REFERENCES category (id);
ALTER TABLE notifications     ADD CONSTRAINT fk_notifications_user     FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE order_detail      ADD CONSTRAINT fk_order_detail_order     FOREIGN KEY (order_id) REFERENCES orders (id);
ALTER TABLE order_detail      ADD CONSTRAINT fk_order_detail_product   FOREIGN KEY (product_id) REFERENCES product (id);
ALTER TABLE orders            ADD CONSTRAINT fk_orders_user            FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE payments          ADD CONSTRAINT fk_payments_order         FOREIGN KEY (order_id) REFERENCES orders (id);
ALTER TABLE posts             ADD CONSTRAINT fk_posts_author           FOREIGN KEY (author_id) REFERENCES users (id);
ALTER TABLE posts             ADD CONSTRAINT fk_posts_category         FOREIGN KEY (category_id) REFERENCES post_categories (id);
ALTER TABLE product           ADD CONSTRAINT fk_product_brand          FOREIGN KEY (brand_id) REFERENCES brand (id);
ALTER TABLE product           ADD CONSTRAINT fk_product_category       FOREIGN KEY (category_id) REFERENCES category (id);
ALTER TABLE product_image     ADD CONSTRAINT fk_product_image_product  FOREIGN KEY (product_id) REFERENCES product (id);
ALTER TABLE role_permissions  ADD CONSTRAINT fk_role_perm_permission   FOREIGN KEY (permissions_id) REFERENCES permission (name);
ALTER TABLE role_permissions  ADD CONSTRAINT fk_role_perm_role         FOREIGN KEY (role_id) REFERENCES role (name);
ALTER TABLE service_image     ADD CONSTRAINT fk_service_image_service  FOREIGN KEY (service_id) REFERENCES professional_service (id);
ALTER TABLE user_roles        ADD CONSTRAINT fk_user_roles_role        FOREIGN KEY (role_id) REFERENCES role (name);
ALTER TABLE user_roles        ADD CONSTRAINT fk_user_roles_user        FOREIGN KEY (user_id) REFERENCES users (id);

-- ---------------------------- Index ----------------------------
-- 3 index dưới đây khai báo trong @Table(indexes = ...) của ChatMessage/Notification

CREATE INDEX idx_chat_message_conversation ON chat_messages (conversation_id, created_at);
CREATE INDEX idx_notification_user_read    ON notifications (user_id, is_read);
CREATE INDEX idx_notification_user_created ON notifications (user_id, created_at);
