-- payOS bắt buộc orderCode là số nguyên và không nhận trùng, nên không dùng lại
-- được orders.order_code (dạng DH...). Mỗi lần mở link thanh toán mới lấy một số
-- từ sequence này.
CREATE SEQUENCE payos_order_code_seq;

-- Một đơn có thể có nhiều link theo thời gian (link cũ hết hạn -> tạo link mới).
-- Giữ lại mọi link để tiền trả vào link cũ vẫn tra ngược ra được đơn hàng.
CREATE TABLE payos_payment_links (
    id               bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id         varchar(255)  NOT NULL,
    payos_order_code bigint        NOT NULL UNIQUE,
    payment_link_id  varchar(255)  NOT NULL UNIQUE,
    checkout_url     varchar(1024) NOT NULL,
    expires_at       timestamp(6)  NOT NULL,
    created_at       timestamp(6),
    updated_at       timestamp(6),
    PRIMARY KEY (id)
);

CREATE INDEX ix_payos_payment_links_order ON payos_payment_links (order_id);

ALTER TABLE payos_payment_links
    ADD CONSTRAINT fk_payos_payment_links_order
    FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE;
